kind: Namespace
apiVersion: v1
metadata:
  name: echo
  labels:
    name: echo

---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: echo-deployment
  namespace: echo
  labels:
    app: echo-server
spec:
  replicas: 2
  selector:
    matchLabels:
      app: echo-server
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        app: echo-server
    spec:
      containers:
        - image: australia-southeast2-docker.pkg.dev/deft-duality-350018/docker-registry/ealen/echo-server
          name: echo-container
          resources:
            requests:
              cpu: "250m"
              memory: "512M"
          ports:
            - containerPort: 80
              name: echo-port
          env:
            - name: ENVVARNAME
              value: ENVVARVALUE
      restartPolicy: Always

---
kind: MultiClusterService
apiVersion: networking.gke.io/v1
metadata:
  name: echo-service
  namespace: echo
spec:
  template:
    spec:
      selector:
        app: echo-server
      ports:
        - name: web
          protocol: TCP
          port: 80
          targetPort: 80

---
kind: MultiClusterIngress
apiVersion: networking.gke.io/v1
metadata:
  name: echo-ingress
  namespace: echo
spec:
  template:
    spec:
      backend:
        serviceName: echo-service
        servicePort: 80
      rules:
        - host: echo.chaoscross.xyz
          http:
            paths:
              - backend:
                  serviceName: echo-service
                  servicePort: 80
                path: /
